#!/usr/bin/env bash
# Mint all cards from cardData.json via WhirlpoolRouter.createCard
# Expects metadata files at cog-works/public/data/metadata/<index>.json
# (generated by generate-metadata.py)
set -e
export PATH="$HOME/.foundry/bin:$PATH"

ROUTER="${1:?Usage: mint-all-cards.sh <ROUTER_ADDRESS>}"
RPC="http://127.0.0.1:8545"
PK="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
CARD_DATA="$HOME/Projects/cog-works/public/data/cardData.json"
META_DIR="$HOME/Projects/cog-works/public/data/metadata"

if [ ! -f "$CARD_DATA" ]; then
  echo "ERROR: cardData.json not found at $CARD_DATA"
  exit 1
fi

# Generate metadata files first
echo "Generating ERC-721 metadata files..."
python3 "$HOME/Projects/erc-1142/scripts/generate-metadata.py"
echo ""

TOTAL=$(python3 -c "import json; print(len(json.load(open('$CARD_DATA'))))")
echo "Minting $TOTAL cards..."
echo ""

MINTED=0
FAILED=0

# Extract name + symbol per card, mint with metadata URI pointing to dev server
python3 -c "
import json, sys

cards = json.load(open('$CARD_DATA'))
for i, card in enumerate(cards):
    name = card.get('name', f'Card_{i}')
    # Symbol: first letter of each word, uppercase, max 8 chars
    words = name.split()
    symbol = ''.join(w[0].upper() for w in words if w)
    if len(symbol) < 2:
        symbol = name.upper().replace(' ', '')[:4]
    symbol = symbol[:8]
    # URI points to metadata file served by vite dev server
    uri = f'/data/metadata/{i}.json'
    print(f'{i}\t{name}\t{symbol}\t{uri}')
" | while IFS=$'\t' read -r IDX NAME SYMBOL URI; do
  NUM=$((IDX + 1))
  echo -n "[$NUM/$TOTAL] $NAME ($SYMBOL)... "
  if cast send "$ROUTER" "createCard(string,string,string)" "$NAME" "$SYMBOL" "$URI" \
    --value 0.05ether --private-key "$PK" --rpc-url "$RPC" --quiet 2>/dev/null; then
    echo "✓"
    MINTED=$((MINTED + 1))
  else
    echo "✗ FAILED"
    FAILED=$((FAILED + 1))
  fi
done

echo ""
echo "Done! Minted from $TOTAL cards in cardData.json."
echo "Metadata files: $META_DIR/*.json"
